import {readFileSync,writeFileSync} from 'node:fs';
import {allocationCommitment} from './score.mjs';
const dust=JSON.parse(readFileSync(new URL('./snapshots/locked-dust.json',import.meta.url)));
const rows=[{sui:'0x'+ 'a'.padStart(64,'0'),amountBaseUnits:dust.amountBaseUnits,lockMonths:dust.lockMonths},{sui:'0x'+ 'b'.padStart(64,'0'),amountBaseUnits:'1000000',lockMonths:12}];
const hash='vector['+Buffer.from(allocationCommitment(rows),'hex').join(',')+']';
const source=`/// Generated by scripts/feast/generate_move_fixture.mjs from scorer fixtures.
#[test_only]
module viper::feast_golden;
use viper::feast;
use viper::lock_vault;
use viper::v1per::V1PER;
#[test]
fun generated_dust_and_multibatch_hash_parity() {
    let mut ctx=sui::tx_context::dummy();let mut clock=sui::clock::create_for_testing(&mut ctx);
    assert!(lock_vault::full_reward(${dust.amountBaseUnits},${dust.requestedMonths})==${dust.fullReward});
    let (mut pool,cap)=feast::create(sui::coin::mint_for_testing<V1PER>(viper::allocation::public_reserve(),&mut ctx),&clock,&mut ctx);
    let (mut vault,vcap)=lock_vault::create(sui::coin::mint_for_testing<V1PER>(viper::allocation::lock_rewards(),&mut ctx),@0xC,@0xF,0,&mut ctx);
    let (mut currency,metadata)=viper::v1per::test_currency(&mut ctx);
    let hash=${hash};
    feast::set_allocations(&mut pool,&cap,vector[@0xA],vector[${dust.amountBaseUnits}],vector[${dust.lockMonths}],hash,2,true,&clock);
    feast::set_allocations(&mut pool,&cap,vector[@0xB],vector[1000000],vector[12],hash,2,false,&clock);
    sui::clock::set_for_testing(&mut clock,7*86400000);
    feast::finalize(&mut pool,&cap,&mut vault,&mut currency,hash,&clock);
    let (inventory,allocated,_,burned)=feast::accounting(&pool);assert!(allocated==1000001 && inventory==allocated && burned==viper::allocation::public_reserve()-allocated);
    std::unit_test::destroy(pool);std::unit_test::destroy(cap);std::unit_test::destroy(vault);std::unit_test::destroy(vcap);std::unit_test::destroy(currency);std::unit_test::destroy(metadata);sui::clock::destroy_for_testing(clock);
}
#[test,expected_failure(abort_code=6,location=viper::feast)]
fun changed_csv_row_cannot_finalize() {
    let mut ctx=sui::tx_context::dummy();let mut clock=sui::clock::create_for_testing(&mut ctx);
    let (mut pool,cap)=feast::create(sui::coin::mint_for_testing<V1PER>(viper::allocation::public_reserve(),&mut ctx),&clock,&mut ctx);
    let (mut vault,_vcap)=lock_vault::create(sui::coin::mint_for_testing<V1PER>(viper::allocation::lock_rewards(),&mut ctx),@0xC,@0xF,0,&mut ctx);
    let (mut currency,_metadata)=viper::v1per::test_currency(&mut ctx);let hash=${hash};
    feast::set_allocations(&mut pool,&cap,vector[@0xA,@0xB],vector[2,1000000],vector[0,12],hash,2,true,&clock);
    sui::clock::set_for_testing(&mut clock,7*86400000);feast::finalize(&mut pool,&cap,&mut vault,&mut currency,hash,&clock);abort 999
}
`;
const target=new URL('../../viper/sources/feast_golden.move',import.meta.url);
if(process.argv.includes('--check')) {
 if(readFileSync(target,'utf8')!==source)throw Error('Move Feast fixture differs from scorer commitment/dust fixture; regenerate and review it.');
} else writeFileSync(target,source);
