/// Generated by scripts/feast/generate_move_fixture.mjs from scorer fixtures.
#[test_only]
module viper::feast_golden;
use viper::feast;
use viper::lock_vault;
use viper::v1per::V1PER;
#[test]
fun generated_dust_and_multibatch_hash_parity() {
    let mut ctx=sui::tx_context::dummy();let mut clock=sui::clock::create_for_testing(&mut ctx);
    assert!(lock_vault::full_reward(1,12)==0);
    let (mut pool,cap)=feast::create(sui::coin::mint_for_testing<V1PER>(viper::allocation::public_reserve(),&mut ctx),&clock,&mut ctx);
    let (mut vault,vcap)=lock_vault::create(sui::coin::mint_for_testing<V1PER>(viper::allocation::lock_rewards(),&mut ctx),@0xC,@0xF,0,&mut ctx);
    let (mut currency,metadata)=viper::v1per::test_currency(&mut ctx);
    let hash=vector[141,6,58,92,157,179,82,202,246,245,38,234,3,148,246,148,54,190,94,157,240,135,76,43,39,45,219,72,3,149,181,61];
    feast::set_allocations(&mut pool,&cap,vector[@0xA],vector[1],vector[0],hash,2,true,&clock);
    feast::set_allocations(&mut pool,&cap,vector[@0xB],vector[1000000],vector[12],hash,2,false,&clock);
    sui::clock::set_for_testing(&mut clock,7*86400000);
    feast::finalize(&mut pool,&cap,&mut vault,&mut currency,hash,&clock);
    let (inventory,allocated,_,burned)=feast::accounting(&pool);assert!(allocated==1000001 && inventory==allocated && burned==viper::allocation::public_reserve()-allocated);
    std::unit_test::destroy(pool);std::unit_test::destroy(cap);std::unit_test::destroy(vault);std::unit_test::destroy(vcap);std::unit_test::destroy(currency);std::unit_test::destroy(metadata);sui::clock::destroy_for_testing(clock);
}
#[test,expected_failure(abort_code=6,location=viper::feast)]
fun changed_csv_row_cannot_finalize() {
    let mut ctx=sui::tx_context::dummy();let mut clock=sui::clock::create_for_testing(&mut ctx);
    let (mut pool,cap)=feast::create(sui::coin::mint_for_testing<V1PER>(viper::allocation::public_reserve(),&mut ctx),&clock,&mut ctx);
    let (mut vault,_vcap)=lock_vault::create(sui::coin::mint_for_testing<V1PER>(viper::allocation::lock_rewards(),&mut ctx),@0xC,@0xF,0,&mut ctx);
    let (mut currency,_metadata)=viper::v1per::test_currency(&mut ctx);let hash=vector[141,6,58,92,157,179,82,202,246,245,38,234,3,148,246,148,54,190,94,157,240,135,76,43,39,45,219,72,3,149,181,61];
    feast::set_allocations(&mut pool,&cap,vector[@0xA,@0xB],vector[2,1000000],vector[0,12],hash,2,true,&clock);
    sui::clock::set_for_testing(&mut clock,7*86400000);feast::finalize(&mut pool,&cap,&mut vault,&mut currency,hash,&clock);abort 999
}
