/// Generated by scripts/generate_reward_schedule.py. Immutable total-term ppm rates.
module viper::reward_schedule;
public fun rate_ppm(months: u64): u64 {
    assert!(months >= 1 && months <= 24, 1);
    let rates = vector[5000, 5526, 6108, 6751, 7462, 8248, 9116, 10076, 11137, 12310, 13606, 15039, 16622, 18373, 20307, 22446, 24809, 27422, 30309, 33500, 37028, 40927, 45236, 50000];
    rates[months - 1]
}
