/// Generated by scripts/generate_reward_schedule.py. Immutable annual ppm rates.
module viper::reward_schedule;
public fun rate_ppm(months: u64): u64 {
    assert!(months >= 1 && months <= 24, 1);
    let rates = vector[10000, 11052, 12216, 13503, 14924, 16496, 18233, 20153, 22275, 24620, 27213, 30078, 33245, 36746, 40615, 44892, 49619, 54844, 60618, 67001, 74056, 81854, 90473, 100000];
    rates[months - 1]
}
