"""Generate the exact immutable rate table used by Move and the website.
Total term reward rate = 0.5% * 10 ** ((months - 1) / 23).
Round down to parts per million; integer endpoints are exact.
"""
from decimal import Decimal, localcontext
from pathlib import Path
import json
with localcontext() as context:
    context.prec = 60
    rates = [int(Decimal(5000) * (Decimal(10) ** (Decimal(m - 1) / 23))) for m in range(1, 25)]
rates[-1] = 50000
root = Path(__file__).resolve().parents[1]
(root / 'src/rewardSchedule.json').write_text(json.dumps(rates, indent=2) + '\n')
(root / 'viper/sources/reward_schedule.move').write_text('''/// Generated by scripts/generate_reward_schedule.py. Immutable total-term ppm rates.
module viper::reward_schedule;
public fun rate_ppm(months: u64): u64 {
    assert!(months >= 1 && months <= 24, 1);
    let rates = vector[''' + ', '.join(map(str, rates)) + '''];
    rates[months - 1]
}
''')
print([(m, rates[m-1]/10000) for m in (1, 6, 12, 18, 24)])
