import { siteUrl } from './site';
import LaunchTimeline from './LaunchTimeline';
import FeastPanel from './FeastPanel';
import { FreeClaimsSection, BurnsSection, CommunitySection, FoundationSection, PrivacySection, QuestionsSection } from './ProjectSections';
import { launch, isLaunchConfigured } from './manifest';

export default function Rules() {
  return <div className="site rules-page"><a className="skip-link" href="#status">Skip to rules</a>
    <header className="header"><a className="brand" href={siteUrl('')} aria-label="Viper Coin home"><img src={siteUrl('viper-logo.webp')} alt=""/><span>VIPER<span className="accent">.</span><small>COIN / V1PR</small></span></a><nav aria-label="Rules navigation"><a href={siteUrl('')}>Home</a><a href={siteUrl('whitepaper/')}>White paper</a><a href={siteUrl('monitor/')}>Monitor</a></nav></header>
    <main>
      <section id="status" className="section rules-intro"><div className="kicker">VIPER COIN (V1PR) / RULES & PUBLIC PROOF</div><h1>THE BITE.<br/><em>THE FINE PRINT.</em></h1><p>Viper Coin (V1PR) is pre-launch. Read how participation, rewards and custody work before taking part.</p><p>{isLaunchConfigured ? `Deployment records are configured for Sui ${launch.network}; verify the full coin type and transactions in the monitor. Testnet tokens are not a mainnet launch.` : 'V1PR is not deployed. No verified mainnet coin type or funded trading pool is live; contributions, applications and claims remain closed.'} Nothing on this site promises gains.</p><nav className="rules-index" aria-label="Jump to a rule"><a href="#timeline">Launch timeline</a><a href="#claims">Free claims</a><a href="#feast">The Feast</a><a href="#lock">Lock rules</a><a href="#burns">Burns</a><a href="#community">Community budget</a><a href="#foundation">Foundation</a><a href="#privacy">Privacy</a><a href="#questions">FAQ</a></nav></section>
      <LaunchTimeline />
      <FeastPanel detailed />
      <FreeClaimsSection detailed />
      <section id="lock" className="section feature-section"><div className="kicker">LOCK & EARN / FULL RULES</div><h2>FIRST COME.<br/><em>FULLY FUNDED.</em></h2><div className="rules-prose"><p>The 150 million V1PR reward pool funds accepted locks until available capacity is exhausted. Your full reward is reserved when your lock opens.</p><p>Annual simple token rates grow exponentially from 1% for a 1-month lock to 10% for a 24-month lock. Total reward is annual rate × months / 12: 20% for 24 months. The full term reward is escrowed. There is no new minting.</p><p>One month = 30 days. Simple rewards in V1PR; no compounding or dollar-return promise. No deposit fee. No fee at maturity. Early exit pays the reward for whole completed months and charges up to 5% of principal, tapering continuously to zero. Every completed lock earns a positive net V1PR reward before network gas. Early exits can return less than deposited.</p><p>Early-exit fee = 5% × the fraction of the term remaining. It reaches zero at maturity. Of the fee, 50% is queued for permissionless burning, 40% goes to Community programs and 10% to the V1PR Foundation. Only completed program months earn rewards, at the rate for that completed length.</p><p>A deposit pause never blocks existing exits. Positions cannot be transferred, extended or topped up. Unused early-exit reservations return to capacity; anyone can fund the vault with existing V1PR. New reward-bearing locks stop when the vault cannot reserve the full term reward; existing principal and accepted rewards remain escrowed.</p><p>{isLaunchConfigured ? `Network: ${launch.network}. Wallet approval is required for every transaction.` : 'Contracts are implemented locally. Transactions remain disabled until deployment records and verified object IDs are published.'}</p><a className="text-link" href={siteUrl('#lock')}>Open the calculator →</a></div></section>
      <BurnsSection /><CommunitySection /><FoundationSection /><PrivacySection /><QuestionsSection />
    </main>
    <footer><span>VIPER COIN (V1PR)</span><nav aria-label="Footer navigation"><a href={siteUrl('whitepaper/')}>White paper</a><a href="#foundation">Foundation</a><a href="#privacy">Privacy</a><a href="https://github.com/Robertcurzon/ViperCoin" target="_blank" rel="noreferrer">GitHub ↗</a></nav></footer>
  </div>;
}
